checkpoint:
  save_dir: "checkpoints"
  callback:
    verbose: True
    every_n_train_steps: 10000

wandb:
  project: "hififace"
  entity: "imasug"

trainer:
  gradient_clip_val: 0
  max_epochs: 100000
  num_sanity_val_steps: 1
  fast_dev_run: False
  progress_bar_refresh_rate: 1
  distributed_backend: 'ddp'
  benchmark: True
  limit_val_batches: 0.0
